version: '3.7'

services:
  kontext:
    networks:
      - mariadb
    depends_on:
      - mariadb

  rq-worker:
    networks:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kontext-mariadb
    volumes:
      - mdbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mariadb

volumes:
  mdbdata: {}

networks:
  mariadb: {}