version: '3.7'

services:
  kontext-dev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kontext-dev
    environment:
      - TZ=Europe/Prague
      - DEV_SERVER_HOST=0.0.0.0
      - DEV_PUBLIC_PATH=
    command: bash -c "./scripts/install/conf/docker/run.dev.sh"
    ports:
      # kontext debug port
      - "5678:5678"
    volumes:
      - ${KONTEXT_CONFIG}:/opt/kontext/conf/config.xml
      # we have to bind folders separatelly
      # if we bind whole root, container can't access its node_modules
      - ./lib:/opt/kontext/lib
      - ./locale:/opt/kontext/locale
      - ./scripts:/opt/kontext/scripts
      - ./templates:/opt/kontext/templates
      - ./worker:/opt/kontext/worker
      # similar reason for binding folders
      # we need to share dist files with nginx
      - dist:/opt/kontext/public/files/dist
      - ./public/app.py:/opt/kontext/public/app.py
      - ./public/ws_app.py:/opt/kontext/public/ws_app.py
      - ./public/files/css:/opt/kontext/public/files/css
      - ./public/files/html:/opt/kontext/public/files/html
      - ./public/files/img:/opt/kontext/public/files/img
      - ./public/files/js:/opt/kontext/public/files/js
      - ./public/files/misc:/opt/kontext/public/files/misc
      - ./public/files/themes:/opt/kontext/public/files/themes
      - corpora-data:/var/lib/manatee
      - corpora-cache:/var/local/corpora
    networks:
      - databases
      - kontext
    depends_on: 
      - redis

  rq-worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.rqworker
    environment:
      - TZ=Europe/Prague
    command: bash -c "pip3 install debugpy pyinotify && python3 scripts/dev/reloader.py /opt/kontext py \"python3 -m debugpy --listen 0.0.0.0:5679 /opt/kontext/worker/rqworker.py\""
    ports:
     # rqworker debug port
     - "5679:5679"
    volumes:
      - ${KONTEXT_CONFIG}:/opt/kontext/conf/config.xml
      - ./lib:/opt/kontext/lib
      - ./worker:/opt/kontext/worker
      - ./scripts:/opt/kontext/scripts
      - corpora-data:/var/lib/manatee
      - corpora-cache:/var/local/corpora
    networks:
      - databases
    depends_on:
      - redis
      - kontext-dev

  rq-scheduler:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.rqscheduler
    environment:
      - TZ=Europe/Prague
    command: rqscheduler --host kontext_redis_1 --db 2 -i 10
    networks:
      - databases
    depends_on: 
      - redis

  redis:
    image: redis:latest
    environment:
      - TZ=Europe/Prague
    networks:
      - databases
    ports:
      - "16379:6379"
    volumes:
      - redisdata:/data

  nginx:
    image: nginx:latest
    environment:
      - TZ=Europe/Prague
    ports:
      - "8080:80"
    volumes:
      - ./scripts/install/conf/docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - dist:/opt/kontext/public/files/dist
      - ./public/files/html:/opt/kontext/public/files/html
      - ./public/files/img:/opt/kontext/public/files/img
      - ./public/files/js:/opt/kontext/public/files/js
      - ./public/files/misc:/opt/kontext/public/files/misc
      - ./public/files/themes:/opt/kontext/public/files/themes
    networks:
      - kontext
    depends_on:
      - kontext-dev

volumes:
  dist: {}
  corpora-data: {}
  corpora-cache: {}
  redisdata: {}


networks:
  databases: {}
  kontext: {}