version: "3.7"

services:
  kontext:
    environment:
      - STATUS_SERVICE_URL=${STATUS_SERVICE_URL}

  ws:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ws-jammy
    volumes:
      - ${KONTEXT_CONFIG}:/opt/kontext/conf/config.xml
      - corpora-data:/var/lib/manatee
      - corpora-cache:/var/local/copora
    networks:
      - databases
      - kontext
    depends_on:
      redis:
        condition: service_healthy

  nginx:
    volumes:
      - ./scripts/install/conf/docker/nginx.ws.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      ws: service_started

volumes:
  corpora-data: {}
  corpora-cache: {}

networks:
  databases: {}
  kontext: {}