version: '3.7'
services:
  kontext:
    build: .
    command: gunicorn -c ./scripts/install/conf/docker/gunicorn-conf.py public.app:application
    volumes:
      - ./scripts/install/conf/docker/config.xml:/opt/kontext/conf/config.xml
      - files:/opt/kontext/public/files
      - corpora:/var/local/corpora
    networks:
      - redis
      - kontext
    depends_on: 
      - redis
  redis:
    image: redis:latest
    networks:
      - redis
    ports:
      - "16379:6379"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./scripts/install/conf/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - files:/opt/kontext/public/files
    networks:
      - kontext
    depends_on:
      - kontext
  rq-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.rqscheduler
    networks:
      - redis
    depends_on: 
      - kontext
      - redis
  rq-worker:
    build:
      context: .
      dockerfile: Dockerfile.rqworker
    volumes:
      - ./scripts/install/conf/docker/config.xml:/opt/kontext/conf/config.xml
      - corpora:/var/local/corpora
    networks:
      - redis
    depends_on:
      - redis
      - kontext
volumes:
  files:
  corpora:
networks:
  redis: {}
  kontext: {}