version: '3'

services:
  kontext-test:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kontext

    command: bash -c "pip3 install pulp piwikapi && python3 tests/runtests.py"
    environment:
      - REDIS_HOST=kontext_redis_1
    volumes:
      - ./tests:/opt/kontext/tests
      - ./test-data:/opt/kontext/test-data
    networks:
      - databases
    depends_on:
      - redis

  redis:
    image: redis:latest
    networks:
      - databases

networks:
  databases: {}
