version: '3'

services:
  mariadb-test:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mariadb-cypress
    environment:
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
    hostname: kontext_mariadb_1
    volumes:
      - kontext_testdb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - databases

  kontext:
    volumes:
      - ./scripts/install/conf/docker/config.mysql.xml:/opt/kontext/conf/config.xml
    depends_on:
      - mariadb-test

  rq-scheduler:
    depends_on:
      - mariadb-test

  rq-worker:
    depends_on:
      - mariadb-test

volumes:
  kontext_testdb: {}